# Generated by Django 4.2.18 on 2025-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
