# Generated by Django 4.2.18 on 2025-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='music_genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip-Hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('country', 'Country'), ('reggae', 'Reggae')], default='Unknown Location', max_length=50),
            preserve_default=False,
        ),
    ]
