# Generated by Django 4.2.18 on 2025-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_description_event_bio_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default='123 Default Street Default City Default Postcode'),
            preserve_default=False,
        ),
    ]
