# Generated by Django 4.2.18 on 2025-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_location_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='music_genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip-Hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('country', 'Country'), ('reggae', 'Reggae')], max_length=50, verbose_name='Music Genre'),
        ),
    ]
