# Generated by Django 4.2.18 on 2025-01-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_address_event_city_event_postcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
